### ISSUE TITLE
Set up Node/NPM

### ISSUE THREAD

**Issue by alcapitan** [alcapitan/atui#100]
With these dependencies : 
- PostCSS / Autoprefixer
- Prettier 
- Terser
- Babel
- Live-server

**Comment by alcapitan** [comment]
Needed for other issues and global improvements.

**Comment by alcapitan** [comment]
Partially solved by 231ac367a2402cc5e63e02482fd0dd4b1572755c

**Comment by alcapitan** [comment]
@itsarraj I need help, if you know anything about NPM. I don't understand why my dependencies copy the same css value several times, look at the ruined stylesheets!

**Comment by ghost** [comment]
I understand , I will fix it.

**Comment by ghost** [comment]
I understood the issue remove these dependencies

**Comment by alcapitan** [comment]
> I understood the issue remove these dependencies

You didn't push anything ? What dependencies cause that issue ?

**Comment by ghost** [comment]
devDependencies , i will fix and remove

**Comment by ghost** [comment]
// "prettier:check": "prettier -c **.css **.js **.md **.html --cache",

**Comment by alcapitan** [comment]
Done with 231ac367a2402cc5e63e02482fd0dd4b1572755c c4df3f9abc485932d61f2662d5734ba08805cf16 c3b8efcbe7d70bfb4e608c153d57b22d37fb3d3b .

**Comment by alcapitan** [comment]
> devDependencies , i will fix and remove

@itsarraj
I resolved my own config.
I know it's heavy, but I will clear it later in the development steps.
