### ISSUE TITLE
Fix a lot of small bogues

### ISSUE THREAD

**Issue by alcapitan** [alcapitan/atui#121]
- [x] Margin inconsistencies on bottom bar of the header.
- [x] Cards are too much big depending for the size of the screen.
- [x] Header hide content behind if there is no carousel.
- [x] Texts with fonts title can be unreadable when they are bold.
- [x] Textarea dimension style avoid HTML attributes working.
- [x] Margin inconsistencies for elements in paragraph.
- [x] Not all elements are marged in paragraph.
- [ ] Set gray background behind images.
- [x] Texts in Boxes unreadable with dark mode.

**Comment by Gungun1643** [comment]
What should be the size of the cards according to you i.e 4cards / page  or 2 cards/page??

**Comment by alcapitan** [comment]
> What should be the size of the cards according to you i.e 4cards / page or 2 cards/page??

I found another way to resize the cards, I will do myself because I've the idea.
