### ISSUE TITLE
A bundle of small improvements

### ISSUE THREAD

**Issue by alcapitan** [alcapitan/atui#122]
- [x] Normalize margin and border-radius like font-size.
- [x] Add JS function for better access to Clipboard API.
- [x] Add JS function for better access to Share API.
- [x] Text selection with accent color.
- [x] Pill option style for inputs.
- [x] Rich links support in meta HTML tag.

**Comment by ghost** [comment]
i can help in that

**Comment by alcapitan** [comment]
> i can help in that

Hello, 

Thanks for your proposition ! You're the first foreign person who meet me in GitHub.
Actually, I'm used to work alone, and I have some personal ideas and code for some other issues.

So, you can help me for the tasks above, except for "Pill option style for inputs" task.
Take mostly a look for tasks in v0.3 milestone.
Moreover, you can also suggest me your own feature ideas.

Please keep me informed about your wishes,
